### ISSUE TITLE
“Charge token missing” error on not confirming transaction

### ISSUE THREAD

**Issue by brblakley** [CardFlight/cardflight-ios#33] opened 2016-03-23 00:45 UTC
Steps to reproduce (using CardFlight iOS SDK 3.1):
- Call `-[CFTSessionManager setApiToken:accountToken:]` with an EMV-compatible account’s tokens.
- Connect an EMV-compatible reader.
- In `-[CFTReaderDelegate readerIsConnected:withError:]`, call `-[CFTReader beginEMVTransactionWithAmount:andChargeDictionary:]`.
- Dip a chip card as prompted.
- In `-[CFTReaderDelegate emvCardResponse:]`, call `[reader emvProcessTransaction:NO]`.

Expected result: `-[CFTReaderDelegate emvErrorResponse:]` not called or called with an error about the transaction being canceled due to not confirming the transaction.

Actual result: `-[CFTReaderDelegate emvErrorResponse:]` called with: `Error Domain=CardFlight Code=466 "Charge token missing" UserInfo={NSLocalizedDescription=Charge token missing}`

**Comment by hokiewalrus** [comment] 2016-04-15 15:59
I am unable to reproduce. 

@brblakley Can you share more details about the code you use to reproduce the error?

**Comment by brblakley** [comment] 2016-04-18 20:57
@hokiewalrus, here’s a rough sample app that demonstrates the issue:
https://github.com/CardFlight/cardflight-ios/files/224784/Demo.zip

And here are instructions for reproducing it with that sample app:
- Run `pod install`.
- In `-[ViewController viewDidLoad]`, enter tokens for an EMV-compatible account.
- Product > Run.
- Wait until the console reports “is EMV ready:Yes”.
- Connect an EMV-compatible reader.
- Wait until the console reports “ViewController readerIsConnected:YES withError:(null)”. 
- Tap the “Begin Transaction” button.
- Dip a chip card.
- In the “Confirm Payment” alert, tap Cancel.
- Check the console for the error: “ViewController emvErrorResponse:Error Domain=CardFlight Code=466 "Charge token missing" UserInfo={NSLocalizedDescription=Charge token missing}”

**Comment by hokiewalrus** [comment] 2016-11-04 18:33
This issue has been fixed in version 3.5

**Closed by hokiewalrus** 2016-11-04 18:33 UTC
