### ISSUE TITLE
Cancelling an emv transaction results in confusing UI message

### ISSUE THREAD

**Issue by lzell** [CardFlight/cardflight-ios#57] opened 2016-06-20 23:38 UTC
Repro:

1. Implement the following delegate methods:

    -emvCardResponse:cardDictionary:
    -emvCardRemoved:
    -emvMessage:

2. Cancel an emv transaction in the body of `-emvCardResponse:cardDictionary:` by passing false to `-emvProcessTransaction`
3. The `-emvMessage:` method will be invoked with a message telling you the transaction was cancelled. Great!
4. The `-emvMessage:` method will be invoked _again_ with a message telling you to remove the card
5. Remove the card
6. The `-emvCardRemoved` method will be invoked as expected
7. The `-emvMessage:` method will be invoked with message: "Declined"

I find number seven confusing from an end-user perspective. I would expect the last message to me to be "Cancelled". Or even, "Cancelled, please remove your card".

Very related: when is the appropriate time to show the user the "remove card" message? Is it before the user authorizes the charge (ostensibly by accepting the details presented to the UI as part of the cardDictionary)?  Or is the card supposed to remain dipped while the user is tapping "ok" on the screen with the card details that we present to them?

**Comment by hokiewalrus** [comment] 2016-06-23 18:16
@lzell Our guidance is that you should obey the messages returned by the SDK and show them as they come. So the SDK will govern when the "remove card" message is displayed. Prompting to remove the card prematurely will result in transactions being declined (as per the EMV spec)

**Comment by hokiewalrus** [comment] 2016-06-23 19:27
Duplicate of #47

**Closed** 2016-06-23 19:26 UTC
Labels: duplicate
